spring.application.name=PaseoApp
# 1. Credenciales y ruta de la base de datos H2 en memoria
# ==== H2 DATABASE ====
# Dirección base de datos
# jdbc:h2:mem: indica que usaremos Java Database Connectivity (jdbc)
# DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE 
# son instrucciones de seguridad para que la base de datos no se apague
spring.datasource.url=jdbc:h2:mem:PaseoAppbd;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
# Le dice a Java exactamente qué archivo usar para poder comunicarse con H2.
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 2. Habilitar la consola web para ver las tablas en el navegador
# ==== JPA / HIBERNATE ====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 3. Comportamiento del traductor ORM (JPA)
# ==== H2 CONSOLE ====
# Prende una interfaz gráfica oculta.
spring.h2.console.enabled=true
# Te dice dónde encontrarla. Cuando prendas tu servidor, 
#podrás ir a tu navegador web, escribir http://localhost:8080/h2-console
spring.h2.console.path=/h2-console